name: Update OFAC list

on:
  workflow_dispatch
  schedule:
    # daily
    - cron: '0 9 * * *'

jobs:
  update-ofac-list:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4

      - run: npm install

      - run: npm run update-ofac-list

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
